services:
  - type: web
    name: raizes-edu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn meu_projeto.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: meu_projeto.settings
      - key: SECRET_KEY
        value: 3.11
